achievements.achievement_type.*:
  type: config_entity
  label: 'Achievement type config'
  mapping:
    id:
      type: string
      label: 'ID'
    title:
      type: label
      label: 'Title'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'
    storage:
      type: string
      label: 'Storage'
    secret:
      type: boolean
      label: 'Secret'
    invisible:
      type: boolean
      label: 'Invisible'
    manual_only:
      type: boolean
      label: 'Manual-only'
    points:
      type: integer
      label: 'Points'
