achievements.achievement_entity.*:
  type: config_entity
  label: 'Achievement entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'
    storage:
      type: string
      label: 'Storage'
    secret:
      type: boolean
      label: 'Secret'
    invisible:
      type: boolean
      label: 'Invisible'
    manual_only:
      type: boolean
      label: 'Manual-only'
    points:
      type: integer
      label: 'Points'
    use_default_image:
      type: boolean
      label: 'Use default image'
    image_path:
      type: string
      label: 'Image path'
